Update stats.md
Lambosaurus/hives-and-torches pull request #17
Opened 2021-11-29 09:16 UTC by LouderthanThunder

Fleshing out stats and what they mean

2021-11-29 10:45 UTC, Lambosaurus commented
I pushed a commit merging this with some of my content. A fair bit got rewritten and moved in the process.

2021-11-30 05:59 UTC, Hoppelite requested changes
Just a couple touch ups

2021-11-30 05:59 UTC, Hoppelite commented on systems/stats.md
> +These attributes intrinsic to your character. They represent the base capabilities of your body and mind. These will only change rarely throughout a characters journey.
Missing 'are'

2021-11-30 05:59 UTC, Hoppelite commented on systems/stats.md
> +These are all recorded as a numeric modifier. An attribute of `0` represents an unexceptional value that a non adventuring human citizen might have.
Specifying human in a potentially non human world. Maybe just person or character

2021-11-30 05:59 UTC, Hoppelite commented on systems/stats.md
> +A character with high will . They are resistant to [spells](spells.md)
Something seems to be missing here

2021-11-30 07:17 UTC, Lambosaurus commented on systems/stats.md
> +A character with high will . They are resistant to [spells](spells.md)
I forgot to delete that line

2021-11-30 07:27 UTC, merged